version: "3"
services:
  web:
    build: .
    container_name: dg01
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn backend.wsgi -b 0.0.0.0:8000"
    environment:
      - DATABASE_URL=postgres_url
      - DEBUG_DJANGO=true
      - AWS_SECRET_KEY=secret_key
      - AWS_ACCESS_KEY=access_key
      - AWS_S3_REGION=region
      - S3_ENV=test
      - BUCKET_NAME=test-bucket
    volumes:
      - ./src:/src
    expose:
      - "8000"
    restart: unless-stopped
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - URL=telepathology.ml
      - SUBDOMAINS=www,
      - VALIDATION=http
      - EMAIL=shubham.rathi97@gmail.com
      - DHLEVEL=2048
      - STAGING=false
    volumes:
      - ../config_dir:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    depends_on:
      - web