# Generated by Django 2.2.4 on 2019-08-13 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0007_auto_20190813_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_sample', to='Images.ImageBatch'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='operator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_sample', to='Operator.Operator'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_sample', to='Sample.Patient'),
        ),
        migrations.AlterField(
            model_name='samplecomment',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sample.Sample'),
        ),
        migrations.AlterField(
            model_name='samplereview',
            name='doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_reviewed_sample', to='Doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='samplereview',
            name='sample_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_reviews', to='Sample.Sample'),
        ),
    ]
