# Generated by Django 2.2.4 on 2019-08-09 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sample', '0001_initial'),
        ('Operator', '0001_initial'),
        ('Address', '0001_initial'),
        ('Doctor', '0001_initial'),
        ('Images', '0002_batchcomment_comment_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplereview',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor_reviewed_sample', to='Doctor.Doctor'),
        ),
        migrations.AddField(
            model_name='samplereview',
            name='sample_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_reviews', to='Sample.Sample'),
        ),
        migrations.AddField(
            model_name='sample',
            name='batch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='batch_sample', to='Images.ImageBatch'),
        ),
        migrations.AddField(
            model_name='sample',
            name='operator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operator_sample', to='Operator.Operator'),
        ),
        migrations.AddField(
            model_name='sample',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_sample', to='Sample.Patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Address.Address'),
        ),
    ]
