# Generated by Django 2.2.4 on 2019-08-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
        ('Sample', '0003_auto_20190811_1636'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='samplereview',
            unique_together={('sample_id', 'doctor_id')},
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['mobile'], name='mobile_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['operator_id'], name='operator_id_idx'),
        ),
        migrations.AddIndex(
            model_name='samplecomment',
            index=models.Index(fields=['sample'], name='sample_idx'),
        ),
        migrations.AddIndex(
            model_name='samplecomment',
            index=models.Index(fields=['comment_by'], name='comment_by_idx'),
        ),
        migrations.AddIndex(
            model_name='samplereview',
            index=models.Index(fields=['sample_id'], name='sample_id_idx'),
        ),
        migrations.AddIndex(
            model_name='samplereview',
            index=models.Index(fields=['doctor_id'], name='doctor_id_idx'),
        ),
    ]
