# Generated by Django 2.2.4 on 2019-08-12 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0004_auto_20190811_1813'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='samplecomment',
            name='sample_idx',
        ),
        migrations.RemoveIndex(
            model_name='samplereview',
            name='sample_id_idx',
        ),
        migrations.RemoveField(
            model_name='samplecomment',
            name='sample',
        ),
        migrations.AddField(
            model_name='sample',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_sample', to='Sample.SampleComment'),
        ),
        migrations.AddField(
            model_name='sample',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, related_name='review_sample', to='Sample.SampleReview'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_sample', to='Sample.Patient'),
        ),
        migrations.AlterUniqueTogether(
            name='samplereview',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='samplereview',
            name='sample_id',
        ),
    ]
