# Generated by Django 2.2.4 on 2019-08-13 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0005_auto_20190812_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='reviews',
        ),
        migrations.AddField(
            model_name='samplecomment',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sample.Sample'),
        ),
        migrations.AddField(
            model_name='samplereview',
            name='sample_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_reviews', to='Sample.Sample'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='samplecomment',
            index=models.Index(fields=['sample'], name='sample_idx'),
        ),
        migrations.AddIndex(
            model_name='samplereview',
            index=models.Index(fields=['sample_id'], name='sample_id_idx'),
        ),
    ]
