# Generated by Django 2.2.4 on 2019-08-14 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0008_auto_20190813_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplereview',
            name='sample_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_reviews', to='Sample.Sample'),
        ),
    ]
