# Generated by Django 2.2.4 on 2019-08-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0002_batchcomment_comment_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BatchComment',
        ),
    ]
