# Generated by Django 2.2.4 on 2019-08-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0003_delete_batchcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='URL',
            new_name='url',
        ),
    ]
